# Generated by Django 4.1.6 on 2023-02-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('history_app', '0001_initial'),
        ('app_ufc', '0003_socialmedia_trainer_delete_feedback_delete_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turnir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history_app.turnir')),
            ],
        ),
        migrations.CreateModel(
            name='FutureFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photoFutureFees/%Y/%m/%d/', verbose_name='')),
                ('sportman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ufc.sportman')),
                ('turnir', models.ManyToManyField(to='history_app.turnir', verbose_name='')),
            ],
        ),
    ]
