# Generated by Django 4.1.6 on 2023-02-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='')),
                ('pub_date', models.DateTimeField(verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
        migrations.CreateModel(
            name='PeopleTurnir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knowdown', models.CharField(max_length=10, verbose_name='')),
                ('tot_strokes', models.CharField(max_length=10, verbose_name='')),
                ('accent_hits', models.CharField(max_length=10, verbose_name='')),
                ('tr_ground', models.CharField(max_length=10, verbose_name='')),
                ('surr_attemps', models.CharField(max_length=10, verbose_name='')),
                ('turnir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='history_app.turnir', verbose_name='')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
            },
        ),
    ]
