# Generated by Django 4.1.6 on 2023-02-09 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_ufc', '0002_alter_info_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.CharField(max_length=500)),
                ('youtube', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=20, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Ф.И.О тренера')),
                ('image', models.ImageField(upload_to='photoTrainer/%Y/%m/%d/', verbose_name='Фотка Информация о тренере ')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.DeleteModel(
            name='Social',
        ),
        migrations.DeleteModel(
            name='Treiner',
        ),
        migrations.AlterField(
            model_name='contact',
            name='massage',
            field=models.TextField(verbose_name='Сообщения о сотрудничестве'),
        ),
        migrations.AlterField(
            model_name='sportman',
            name='category',
            field=models.CharField(choices=[('w_1', 'Наилегчайший вес'), ('w_2', 'Легчайший вес'), ('w_3', 'Полулёгкий вес'), ('w_4', 'Легкий вес '), ('w_5', 'Полусредний вес'), ('w_6', 'Средний вес'), ('w_7', 'Полутяжёлый вес'), ('w_8', 'Тяжёлый вес')], max_length=3),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='sportman',
            name='trainer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='app_ufc.trainer'),
            preserve_default=False,
        ),
    ]
